### ISSUE TITLE
error for install deepspeed

### ISSUE THREAD

**Issue by yash3056** [intel/intel-extension-for-deepspeed#90]
(pytorch) (base) sdp@ipu:~> pip install deepspeed
Collecting deepspeed
  Using cached deepspeed-0.15.1.tar.gz (1.4 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [37 lines of output]
      [WARNING] Failed to create Level Zero tracer: 2013265921
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-aj_a4pu4/deepspeed_0c1e3df3b9344479a8cbf10e8e92ab3b/setup.py", line 39, in <module>
          from op_builder import get_default_compute_capabilities, OpBuilder
        File "/tmp/pip-install-aj_a4pu4/deepspeed_0c1e3df3b9344479a8cbf10e8e92ab3b/op_builder/__init__.py", line 18, in <module>
          import deepspeed.ops.op_builder  # noqa: F401 # type: ignore
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-install-aj_a4pu4/deepspeed_0c1e3df3b9344479a8cbf10e8e92ab3b/deepspeed/__init__.py", line 25, in <module>
          from . import ops
        File "/tmp/pip-install-aj_a4pu4/deepspeed_0c1e3df3b9344479a8cbf10e8e92ab3b/deepspeed/ops/__init__.py", line 6, in <module>
          from . import adam
        File "/tmp/pip-install-aj_a4pu4/deepspeed_0c1e3df3b9344479a8cbf10e8e92ab3b/deepspeed/ops/adam/__init__.py", line 6, in <module>
          from .cpu_adam import DeepSpeedCPUAdam
        File "/tmp/pip-install-aj_a4pu4/deepspeed_0c1e3df3b9344479a8cbf10e8e92ab3b/deepspeed/ops/adam/cpu_adam.py", line 8, in <module>
          from deepspeed.utils import logger
        File "/tmp/pip-install-aj_a4pu4/deepspeed_0c1e3df3b9344479a8cbf10e8e92ab3b/deepspeed/utils/__init__.py", line 10, in <module>
          from .groups import *
        File "/tmp/pip-install-aj_a4pu4/deepspeed_0c1e3df3b9344479a8cbf10e8e92ab3b/deepspeed/utils/groups.py", line 28, in <module>
          from deepspeed import comm as dist
        File "/tmp/pip-install-aj_a4pu4/deepspeed_0c1e3df3b9344479a8cbf10e8e92ab3b/deepspeed/comm/__init__.py", line 7, in <module>
          from .comm import *
        File "/tmp/pip-install-aj_a4pu4/deepspeed_0c1e3df3b9344479a8cbf10e8e92ab3b/deepspeed/comm/comm.py", line 31, in <module>
          from deepspeed.comm.ccl import CCLBackend
        File "/tmp/pip-install-aj_a4pu4/deepspeed_0c1e3df3b9344479a8cbf10e8e92ab3b/deepspeed/comm/ccl.py", line 11, in <module>
          from deepspeed.ops.op_builder import NotImplementedBuilder
        File "/tmp/pip-install-aj_a4pu4/deepspeed_0c1e3df3b9344479a8cbf10e8e92ab3b/deepspeed/ops/op_builder/__init__.py", line 53, in <module>
          this_module.__dict__[member_name] = builder_closure(member_name)
                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-install-aj_a4pu4/deepspeed_0c1e3df3b9344479a8cbf10e8e92ab3b/deepspeed/ops/op_builder/__init__.py", line 41, in builder_closure
          builder = get_accelerator().get_op_builder(member_name)
                    ^^^^^^^^^^^^^^^^^
        File "/tmp/pip-install-aj_a4pu4/deepspeed_0c1e3df3b9344479a8cbf10e8e92ab3b/deepspeed/accelerator/real_accelerator.py", line 184, in get_accelerator
          ds_accelerator = XPU_Accelerator()
                           ^^^^^^^^^^^^^^^^^
      TypeError: Can't instantiate abstract class XPU_Accelerator with abstract methods available_memory, capture_to_graph, create_graph, export_envs, get_compile_backend, handles_memory_backpressure, is_pinned, is_triton_supported, replay_graph, resolves_data_dependency, set_compile_backend, set_visible_devices_envs, supported_dtypes, use_host_timers, visible_devices_envs
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by yash3056** [comment]
it seems like intel has given up on it
